---
stages:
  - name: prepare-env
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - git clone -b $FLEXIO_SCRIPTS_BRANCH $FLEXIO_SCRIPTS $WORKSPACE/flexio-ci-scripts && export PATH=$PATH:$WORKSPACE/flexio-ci-scripts/bin
      - docker pull $CI_TOOLS_IMAGE
    onlyWhen:
      - branch in (master, develop)

  - name: build
    timeout: 60
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - $HBSHED clean install generate-sources test
      - $HBSHED extract-package -T $EXTRACTED_PACKAGE_PATH
    onlyWhen:
      - branch in (master, develop)

  - name: deploy-package
    timeout: 60
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - $HBSHED publish -S $EXTRACTED_PACKAGE_PATH --registry $JS_REGISTRY --username $JS_REGISTRY_USERNAME --password $JS_REGISTRY_PASSWORD --email $JS_REGISTRY_EMAIL
    onlyWhen:
      - branch in (master, develop)

onSuccess:
  - name: metadata
    timeout: 10
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - $PROJECT_METADATA --filename /project-metadata/project-metadata.json
      - $UPLOAD_PROJECT_METADATA /project-metadata/project-metadata.json
      - $TRIGGER_DOWNSTREAM
    onlyWhen:
      - branch in (master, develop)

  - name: notify-flexio
    exec:
      - $NOTIFY --data-urlencode "status=0" --data-urlencode "current-stage="
    onlyWhen:
      - branch in (master, develop)

onError:
  - name: notify-flexio
    exec:
      - $NOTIFY --data-urlencode "status=1" --data-urlencode "current-stage="



env:
  - FLEXIO_SCRIPTS: git@github.com:Flexio-corp/flexio-ci-scripts.git
  - FLEXIO_SCRIPTS_BRANCH: master

  - EXTRACTED_PACKAGE_PATH: /package

  - PIPELINES_URL: https://pipelines.ci.flexio.io/pipelines
  - DEPENDENCIES_URL: https://dependencies.ci.flexio.io/poomci-dependency-api
  - CI_TOOLS_IMAGE: codingmatters/ci-tools:1.2.0-SNAPSHOT

  - DOCKER_VOLUMES: -v $SRC:/src -v $WORKSPACE/flexio-ci-scripts:/flexio-ci-scripts -v $WORKSPACE/project-metadata:/project-metadata -v $WORKSPACE$EXTRACTED_PACKAGE_PATH:$EXTRACTED_PACKAGE_PATH
  - DOCKER_ENV: --env REPOSITORY_ID="$REPOSITORY_ID" --env REPOSITORY="$REPOSITORY" --env CHECKOUT_SPEC="$CHECKOUT_SPEC" --env M2_LOCAL_REPO="/m2"

  - DOCKER_CMD: docker run --rm
  - DOCKER: $DOCKER_CMD $DOCKER_ENV $DOCKER_VOLUMES $CI_TOOLS_IMAGE
  - HBSHED: $DOCKER hbshed
  - FLEXIO_FLOW: $DOCKER flexio-flow

  - PROJECT_METADATA: $FLEXIO_FLOW poom-ci full-repository-json --repository-id "$REPOSITORY_ID" --repository-name "$REPOSITORY" --repository-checkout-spec "$CHECKOUT_SPEC"
  - UPLOAD_PROJECT_METADATA: $DOCKER /flexio-ci-scripts/bin/upload-project-metadata-from-json.sh $DEPENDENCIES_URL

  - TRIGGER_DOWNSTREAM: docker run --rm $DOCKER_ENV $DOCKER_VOLUMES $CI_TOOLS_IMAGE /usr/local/bin/trigger-downstream.sh $PIPELINES_URL $DEPENDENCIES_URL $REPOSITORY_ID "$REPOSITORY" "$CHECKOUT_SPEC"

  - DOCKER_API_URL: http://172.17.0.1:2375

  - NOTIFY: curl -G "https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca" --data-urlencode "repository=$REPOSITORY" --data-urlencode "branch=$BRANCH" --data-urlencode "pipeline-id=$PIPELINE_ID"

  - JS_REGISTRY: https://verdaccio.ci.flexio.io
  - JS_REGISTRY_USERNAME: flexio-ci
  - JS_REGISTRY_EMAIL: dev@flexio.fr


secrets:
  - name: JS_REGISTRY_PASSWORD
    content: $SRC/.poom-ci-pipeline/verdaccio.pass.enc
    as: var
