export const RECONCILIATION_RULES = Object.freeze(Object.seal({
  REPLACE: 'REPLACE',
  BYPASS: 'BYPASS',
  BYPASS_ONCE: 'BYPASS_ONCE',
  BYPASS_CHILDREN: 'BYPASS_CHILDREN',
  ONLY_CHILDREN: 'ONLY_CHILDREN',
  BYPASS_CHILDREN_ONCE: 'BYPASS_CHILDREN_ONCE',
  RECONCILE_LISTENERS: 'RECONCILE_LISTENERS',
  BYPASS_LISTENERS: 'BYPASS_LISTENERS',
  BYPASS_LISTENERS_ONCE: 'BYPASS_LISTENERS_ONCE',
  FORCE: 'FORCE'
}))
